In [26]:
import numpy as np
import imageio
from keras.models import load_model
from keras import losses
from keras import backend

In [67]:
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

def binary_crossentropy(target, output, from_logits=False):
    if not from_logits:
        output = np.clip(output, 1e-7, 1 - 1e-7)
        output = np.log(output / (1 - output))
    return (target * -np.log(sigmoid(output)) +
            (1 - target) * -np.log(1 - sigmoid(output)))


def categorical_crossentropy(target, output, from_logits=False):
    if from_logits:
        output_new = softmax(output)
    else:
        output_new = output / output.sum(axis=-1, keepdims=True)
    print(output_new)
    output_new = np.clip(output_new, 1e-7, 1 - 1e-7)
    return np.sum(target * -np.log(output_new), axis=-1, keepdims=False)

In [2]:
encoder = load_model("/home/niaki/Code/ImageNet/tiny-imagenet-200/ae1.0.0.2_encoder_lastsigmoid_cce_adadelta_metricscce.h5")

W1025 16:22:51.470316 140424371480384 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1025 16:22:51.490262 140424371480384 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1025 16:22:51.499747 140424371480384 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W1025 16:22:51.586061 140424371480384 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W1025 16:22:51

In [3]:
filename = "/tiny_train16/class0/patch000002"
# filename = "/tiny_test16/class0/patch000026"

In [68]:
y_true = np.load("/home/niaki/Code/ImageNet/tiny-imagenet-200/tiny_sifts" + filename + ".npy")
y_true = y_true.reshape((1,128))
x = imageio.imread("/home/niaki/Code/ImageNet/tiny-imagenet-200" + filename + ".png").reshape(1,16,16,3)
y_pred = encoder.predict(x)
bin_crossentr = binary_crossentropy(y_true, y_pred)
cat_crossentr = categorical_crossentropy(y_true, y_pred)

[[0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125
  0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.0078125 0.

In [61]:
y_true

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,  28.,   8.,   0.,   0.,
          2.,  45., 173., 167.,  48.,  14.,   1.,   1.,   5., 104., 173.,
        173.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,  46.,   8.,   0.,   0.,   2.,
         31., 173., 161.,  82.,  13.,   1.,   0.,   4.,  60., 173., 173.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.]], dtype=float32)

In [62]:
y_pred

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
      dtype=float32)

In [56]:
bin_crossentr

array([[ 1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01,  1.59423847e+01,  1.59423847e+01,
         1.59423847e+01, -4.30444397e+02, -1.11596695e+02,
         1.59423847e+01,  1.59423847e+01, -1.59423847e+01,
        -7.01464905e+02, -2.74209009e+03, -2.64643579e+03,
        -7.49292053e+02, -2.07251007e+02,  1.19209290e-0

In [63]:
cat_crossentr

array([9068.445], dtype=float32)

In [42]:
np.sum(bin_crossentr) + 1395.8346 == cat_crossentr

39887.662725

In [64]:
for i in range(y_true.shape[1]):
    print('{:>12f}{:>12f}{:>12f}'.format(y_true[0, i],y_pred[0, i],bin_crossentr[0, i]))      

    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
    0.000000    1.000000   15.942385
 