In [19]:
import numpy as np
import imageio
from keras.models import load_model
from keras import losses
from keras import backend

In [2]:
encoder = load_model("/home/niaki/Code/ImageNet/tiny-imagenet-200/ae1.0.0.0_encoder_lastsigmoid_bce_adadelta_metricscce.h5")

W1025 12:00:52.260599 139705339180864 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1025 12:00:52.280824 139705339180864 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1025 12:00:52.291276 139705339180864 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W1025 12:00:52.377302 139705339180864 deprecation_wrapper.py:119] From /scratch/tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W1025 12:00:52

In [26]:
filename = "/tiny_train16/class0/patch000002"
# filename = "/tiny_test16/class0/patch000026"

In [27]:
x = imageio.imread("/home/niaki/Code/ImageNet/tiny-imagenet-200" + filename + ".png").reshape(1,16,16,3)

In [28]:
y_true = np.load("/home/niaki/Code/ImageNet/tiny-imagenet-200/tiny_sifts" + filename + ".npy")
y_true = y_true.reshape((1,128))

In [29]:
y_true

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0., 112., 129.,  94.,  20.,
         36.,  49.,  63.,  73., 129., 129., 129.,  24.,  35.,  42.,  39.,
        123.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0., 124.,  92.,  64.,  23.,  58.,
         91.,  84., 129., 129., 129., 109.,  28.,  57.,  84.,  59., 129.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.]], dtype=float32)

In [30]:
y_pred = encoder.predict(x)

In [31]:
y_pred

array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 3.427267e-06, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.00

In [32]:
y_true.shape

(1, 128)

In [33]:
y_pred.shape

(1, 128)

In [17]:
losses.binary_crossentropy(y_true, y_pred)

AttributeError: 'numpy.dtype' object has no attribute 'base_dtype'

In [20]:
backend.binary_crossentropy(y_true, y_pred)

AttributeError: 'numpy.dtype' object has no attribute 'base_dtype'

In [23]:
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

def binary_crossentropy(target, output, from_logits=False):
    if not from_logits:
        output = np.clip(output, 1e-7, 1 - 1e-7)
        output = np.log(output / (1 - output))
    return (target * -np.log(sigmoid(output)) +
            (1 - target) * -np.log(1 - sigmoid(output)))


def categorical_crossentropy(target, output, from_logits=False):
    if from_logits:
        output = softmax(output)
    else:
        output /= output.sum(axis=-1, keepdims=True)
    output = np.clip(output, 1e-7, 1 - 1e-7)
    return np.sum(target * -np.log(output), axis=-1, keepdims=False)

In [34]:
binary_crossentropy(y_true, y_pred)

array([[ 1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
         1.1920929e-07,  1.1920929e-07,  1.1920929e-07,  1.1920929e-07,
        -1.7696047e+03,  2.0792344e+03,  1.5151010e+03,  3.2236191e+02,
         5.8025146e+02,  7.8978668e+02,  1.0154400e+03,  1.1766210e+03,
         2.0792344e+03,  2.0792344e+03,  1.6233030e+03,  3.8683429e+02,
         5.6413336e+02,  6.7696002e+02,  6.2860571e+02,  1.98252

In [39]:
categorical_crossentropy(y_true, y_pred)

array([39887.664], dtype=float32)

In [37]:
bin_cross = binary_crossentropy(y_true, y_pred)
for i in range(y_true.shape[1]):
    print(y_true[0, i], y_pred[0,i], bin_cross[0,i])

0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
0.0 0.0 1.1920929e-07
112.0 0.99999654 -1395.8346
129.0 0.0 2079.2344
94.0 0.0 1515.101
20.0 0.0 322.3619
36.0 0.0 580.25146
49.0 0.0 789.7867

In [38]:
np.sum(bin_cross)

38491.83